### PR TITLE
Fixed Merge Conflict Again 

### PR DESCRIPTION
**Pull request by eugenemccormack**
@ConorBaker @markg4123 @paddycorbett - Please Review and Approve if ok.

DO NOT MERGE until conflicts have been addressed.

### CODE REVIEW

**Comment by ConorBaker** [comment]
Happy with that! Good job lads

**Comment by paddycorbett** [comment]
Confilicts are sorted from what I can see. Previous Pull request had issues with Coding Standards section but Euegne has cleaned and Pushed again

**Comment by markg4123** [comment]
Looks good now, it was my error with the previous merge.

**Comment by eugenemccormack** [comment]
> Looks good now, it was my error with the previous merge.

No worries sure is a learning curve

**Pull request merged**
